"""init schema

Revision ID: 85c42dde4743
Revises: 3a720d000f75
Create Date: 2025-07-02 19:17:50.053943

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = '85c42dde4743'
down_revision: Union[str, Sequence[str], None] = '3a720d000f75'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('strikethrough',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ping_id', sa.Integer(), nullable=False),
    sa.Column('author_id', sa.Integer(), nullable=False),
    sa.Column('anchor_start', sa.Integer(), nullable=False),
    sa.Column('anchor_end', sa.Integer(), nullable=False),
    sa.Column('text', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['consultant.id'], ),
    sa.ForeignKeyConstraint(['ping_id'], ['ping.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('strikethrough')
    # ### end Alembic commands ###
